23MAI1023 Emsemble learning

In [ ]:
# for handling data
import pandas as pd
import numpy as np

In [ ]:
# Modelling
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint

In [ ]:
from pandas import read_csv

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
file_path='/content/drive/MyDrive/breast_cancer_wisconsin.csv'
data = pd.read_csv(file_path)
mapping = {'M': 0, 'B': 1}
data['diagnosis'] = data['diagnosis'].map(mapping)
#data.drop(columns=['radius_mean'], inplace=True)
data.drop(columns=data.columns[-1], inplace=True)

In [ ]:
# Save the DataFrame to a new CSV file
data.to_csv('updated_data.csv', index=False)

In [ ]:
#loading dataset
def load_dataset(fname):
    data=read_csv(fname,header=None)
    dataset=data.values
    X=dataset[:,2:]
    y=dataset[:,1]
    return X,y

In [ ]:
#Train Test split
X,y=load_dataset('updated_data.csv')
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=1)
X_test = np.array(data[1:], dtype=float)
#X_test=X_test.astype(float)
print(X_test.dtype)
print('Train',X_train.shape,y_train.shape)
print('Test',X_test.shape,y_test.shape)

float64
Train (381, 30) (381,)
Test (568, 32) (189,)


In [ ]:
#fitting the model
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
#evaluating the model
X_test = X_test[:, :30]
X_test = X_test[:y_test.shape[0]]
y_pred = rf.predict(X_test)

In [ ]:
#accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.6402116402116402


In [ ]:
#hyperparameter tuning
param_dist = {'n_estimators': randint(50,500),
              'max_depth': randint(1,20)}

# Create a random forest classifier
rf = RandomForestClassifier()

# Use random search to find the best hyperparameters
rand_search = RandomizedSearchCV(rf,
                                 param_distributions = param_dist,
                                 n_iter=5,
                                 cv=5)

# Fit the random search object to the data
rand_search.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_iter=5,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x794b4decbeb0>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x794b8c900550>})

In [ ]:
# Create a variable for the best model
best_rf = rand_search.best_estimator_

# Print the best hyperparameters
print('Best hyperparameters:',  rand_search.best_params_)

Best hyperparameters: {'max_depth': 16, 'n_estimators': 127}


In [ ]:
#Evaluation Metrics
# Generate predictions with the best model
y_pred = best_rf.predict(X_test)

# Create the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

print("accuracy =", accuracy_score(y_test, y_pred))
print("precision =", precision_score(y_test, y_pred,average='micro'))
print("recall =", recall_score(y_test, y_pred,average='micro'))

[[  0  67   0]
 [  5 116   0]
 [  0   1   0]]
accuracy = 0.6137566137566137
precision = 0.6137566137566137
recall = 0.6137566137566137
